import React, { useEffect } from "react";

const cards = [
  {
    id: 1,
    image: "/img/ventilation1.jpg",
    title: "Industrial Blowers",
    text: "Blowers are mechanical or electro-mechanical devices used to induce gas flow through ducting, electronics chassis, process stacks, etc.--wherever flow is needed for exhausting, aspirating, cooling, ventilating, conveying, and so on. See Fans also.",
  },
  {
    id: 2,
    image: "/img/ventilation2.jpg",
    title: "Belt driven exhaust fan",
    text: "Belt driven exhaust fans and shutters are made of steel and aluminium for long lasting dependability. Units feature permanently lubricated drive shaft bearings and belt drives for durability.",
  },
  {
    id: 3,
    image: "/img/ventilation3.jpg",
    title: "Industrial exhaust fan",
    text: "Industrial exhaust fans are made of aluminium and steel for long lasting durability and dependability. Units regulate ventilation flow, prevent external air entry and deter intrusion.",
  },
  {
    id: 4,
    image: "/img/ventilation4.jpg",
    title: "Low noise axial inline fan",
    text: "Axial Inline exhaust fans have a single propeller and are good at moving larger amounts of air at low pressure, that is with a minimum of restrictions to air flow, like short lengths of duct, few bends, no branches, etc.",
  },
  {
    id: 5,
    image: "/img/ventilation5.jpg",
    title: "Spiral duct",
    text: "spiral duct systems can keep filtering, heating, cooling, and distributing conditioned air to a minimum that includes round, oval, and flat oval configurations,which exhibits a very high level of air tightness.",
  },
  {
    id: 6,
    image: "/img/ventilation6.jpg",
    title: "Inline fan",
    text: "Inline fan models are applied to a wide range of supply or exhaust applications in commercial and industrial environments. Various impeller types and performances are available to provide models suitable for clean air to sound sensitive to heavy duty industrial uses mounted in the ceiling or on the floor.",
  },
  {
    id: 7,
    image: "/img/ventilation7.jpg",
    title: "Jet fan",
    text: "Jet Fans are used to ventilate and extract smoke from enclosed / underground car parks and basements. Our Jet Fans have the highest thrust to consumed power ratio in the industry! Jet Fans provide the ability to ventilate and extract smoke without using any ducts resulting in tremendous cost savings, power savings and increased installation efficiency. Jet Fans can be used for normal ventilation and also for smoke extract in case of emergencies, or a combination of both.",
  },
  {
    id: 8,
    image: "/img/ventilation8.jpg",
    title: "Industrial Blowers",
    text: "Air handler is usually a large metal box containing a blower, heating or cooling elements, filter racks or chambers, sound attenuators, and dampers. Air handlers usually connect to a ductwork ventilation system that distributes the conditioned air through the building and returns it to the AHU.",
  },
  {
    id: 9,
    image: "/img/ventilation9.jpg",
    title: "H.E.P.A. FILTERS.",
    text: "High efficiency particulate air (HEPA), originally called high-efficiency particulate absorber but also sometimes called high-efficiency particulate arresting or high-efficiency particulate arrestance, is a type of air filter. Filters meeting the HEPA standard have many applications, including use in medical facilities, automobiles, aircraft and homes.",
  },
  {
    id: 10,
    image: "/img/ventilation10.jpg",
    title: "GRILLES, REGISTERS, DIFFUSERS, LOUVERS",
    text: "Grilles, registers, diffusers and louvers are the aesthetically-functional face of an HVAC system. They are available in an unlimited array of sizes, colors, controls, and configurations and can be custom-designed to suit any project. Along with standard units, specialized units are available for security and fire prevention applications, and designed with special filters for use in hospitals and laboratories.",
  },
  {
    id: 11,
    image: "/img/ventilation11.jpg",
    title: "VARIABLE AIR VOLUME BOXES",
    text: "A VAV terminal unit, often called a VAV box, is a zone-level flow control device. It is a calibrated air damper with an automatic actuator. The VAV terminal unit is connected to either a local or a central control system. Historically, pneumatic control was common place, but electronic direct digital control systems are popular especially for mid-to-large size applications.",
  },
  {
    id: 12,
    image: "/img/ventilation12.jpg",
    title: "SOUND ATTENUATORS",
    text: "Sound attenuators (silencers) are used in HVAC systems to help absorb noise that is generated by fans or other air moving equipments. Kinetics offers the design and engineering assistance to integrate our line of duct silencers, sound attenuators into a system solution.",
  },
  {
    id: 13,
    image: "/img/ventilation13.jpg",
    title: "FIRE & SMOKE DAMPERS",
    text: "Dampers are designed to prevent fire and smoke from spreading from a fire source through the ventilation system and into other parts of the building. Depending on their application, fire dampers have different fire-resistance classes called fire-duration ratings and can be installed in concrete or masonry walls and in lightweight partition walls." ,
  },
];

export default function CardGrid() {
   useEffect(() => {
          window.scrollTo(0, 0);
        }, []);
  return (
    <div className="max-w-7xl mx-auto px-4 py-8">
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6 text-justify">
        {cards.map(({ id, image, title, text }) => (
          <div
            key={id}
            className="bg-white rounded-lg  overflow-hidden flex flex-col"
          >
            <div className=" flex items-center justify-center h-48">
              <img
                src={image}
                alt={title}
                className="max-h-full w-auto object-contain"
              />
            </div>
            <div className="p-4 flex flex-col flex-grow">
              <h3 className="text-lg font-semibold mb-2 font-os">{title}</h3>
              <p className="text-gray-600 flex-grow font-robo">{text}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
